### PR TITLE
Fix build on architectures with unsigned char

### PR DESCRIPTION
**Pull request by pkubaj**
ARM and POWER are affected.

### CODE REVIEW

**Comment by stappersg** [comment]
(Summary:  the proposed patch did get human attention)
```text
-        iface.ifr_name[i] = c as i8;
+        iface.ifr_name[i] = c as libc::c_char;
```

It is the `libc::` that makes me wonder if that will block using `libpnet` in a `no_std` environment.

Would like to known if
```text
-        iface.ifr_name[i] = c as i8;
+        iface.ifr_name[i] = c as c_char;
```
or even
```text
-        iface.ifr_name[i] = c as i8;
+        iface.ifr_name[i] = c;
```
will compile (will work) on _ARM_ and/of _POWERPC_.

(Feel free to render this comment as _just noise_.)

**Comment by pkubaj** [comment]
> (Summary: the proposed patch did get human attention)
> 
> ```
> -        iface.ifr_name[i] = c as i8;
> +        iface.ifr_name[i] = c as libc::c_char;
> ```
> 
> It is the `libc::` that makes me wonder if that will block using `libpnet` in a `no_std` environment.
> 
> Would like to known if
> 
> ```
> -        iface.ifr_name[i] = c as i8;
> +        iface.ifr_name[i] = c as c_char;
> ```

`error[E0412]: cannot find type `c_char` in this scope`

> 
> or even
> 
> ```
> -        iface.ifr_name[i] = c as i8;
> +        iface.ifr_name[i] = c;
> ```

That indeed seems to work.

> 
> will compile (will work) on _ARM_ and/of _POWERPC_.
> 
> (Feel free to render this comment as _just noise_.)

**Comment by infosechoudini** [comment]
can we push a new commit that doesnt have `c_char`?

**Comment by infosechoudini** [comment]
in the future, we'll look into other methods of building cross-os and cross-arch

**Comment by mrmonday** [comment]
Looks good thanks!

**Pull request merged**
