### PR TITLE
packet: add DHCP support

### PR DESCRIPTION
**Pull request by Martichou**
Hi !

In a recent project I ended up needing DHCP packet and found this PR (https://github.com/libpnet/libpnet/pull/386).
With the previous PR closed and the comment from a maintainer that one should reopen a new one if needed, that is what I'm doing right now.

I've used the base of [alexander-clarke](https://github.com/alexander-clarke) and adapted it to fit what the RFC 2131 says.
Any feedback is welcome !

### CODE REVIEW

**Review by stappersg — CHANGES_REQUESTED** [review]
The list of `pub mod`s should be kept sorted alphabetically, the new
```rust
   pub mod dhcp;
```
should go in between
```rust
   pub mod arp;
   pub mod ethernet;
```

**Comment by Martichou** [comment]
> The list of `pub mod`s should be kept sorted alphabetically, the new

Done :)

**Comment by mrmonday** [comment]
Looks good, thanks!

**Comment by eli-front** [comment]
anyone seen this error come up?
```
thread 'main' panicked at 'slice index starts at 108 but ends at 69', /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_packet-0.34.0/src/dhcp.rs:70:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

my code is this (packet comes from datalink)
I've tested the same code with ipv4 & arp, which both work
```
let packet = pnet::packet::ethernet::EthernetPacket::new(packet).unwrap();

match pnet::packet::dhcp::DhcpPacket::new(packet.payload()) {
                    Some(dhcp_packet) => {
                        println!("DhcpPacket: {:?}", dhcp_packet);
                    }
                    None => {
                        println!("Not a DhcpPacket");
                        continue;
                    }
                }
```

**Pull request merged**
