### PR TITLE
Fix documentation with false links.

### PR DESCRIPTION
**Pull request by TurnOfACard**
When calling "cargo doc", cargo dislikes the use of square brackets within doc comments when there is no link and they are not escaped.

Not sure the best way to integrate this within CI to prevent reintroducing warnings.

### CODE REVIEW

**Comment by TurnOfACard** [comment]
I'm not sure that the failed checks are relevant to this pull request, as modifications are to doc comments.

**Comment by mrmonday** [comment]
Hi,

Sorry this has taken so long to get around to.

Could you please rebase this?

**Comment by TurnOfACard** [comment]
I'm not really across best practices for rebasing. So if I have completely ruined this pull request, let me know, and I will fix it.

**Comment by stappersg** [comment]
Yeah, github is surely not git.
@TurnOfACard please make a fresh merge request (and close this one).

What I do:
* Have  a _git clone_  of _github fork_
* Work with git as Linus Torvalds would do
* `git push`
* Dumb down to _github mode_

**Pull request closed without merging**
