### PR TITLE
removing a uselesss println

### PR DESCRIPTION
**Pull request by alexsult**
I forget to remove a useless println from the ipv4.rs file.

### CODE REVIEW

**Comment by mrmonday** [comment]
I should have spotted this in the code review - oops!

I just pushed a big breaking change - to fix this you'll need to modify the ipv4.rs.in file instead.

**Comment by alexsult** [comment]
I've seen the big changes, but the what I did for the #155 isn't in the new ipv4.rs.in file.

**Comment by mrmonday** [comment]
Oh no! It looks like I've managed to lose your changes :(

Let me see if I can recover them. I hope I've not lost anything else...

**Comment by mrmonday** [comment]
You should (Hopefully!) Be able to rebase this pull request now.

**Comment by alexsult** [comment]
Everything is OK.

**Comment by mrmonday** [comment]
Great, thank you!

I'll try and remember to publish a new version later today :)

@homu r+

**Pull request merged**
