### PR TITLE
[WIP] Fix panics when accessing fields of invalid packets

### PR DESCRIPTION
**Pull request by polachok**
https://github.com/libpnet/libpnet/issues/221

### CODE REVIEW

**Comment by mrmonday** [comment]
This is looking good so far - make sure to ping me when you're done so I can review it properly :)

**Comment by polachok** [comment]
@mrmonday Please, take a look.

**Comment by mrmonday** [comment]
Looks good to me - are you ready for it to be merged?

**Comment by polachok** [comment]
Sure

**Comment by mrmonday** [comment]
@homu r+

Good work, thanks!

**Pull request merged**
