### PR TITLE
Rewrite #[packet] from syntex to proc macro v0.2

### PR DESCRIPTION
**Pull request by chifflier**
This is a followup from discussion in #355 (let's make this a pull request!)

Here is a description of the PR:

Refactor the `#[packet]` attribute, previously based on a `syntex` compiler plugin, into a "classical" proc-macro based on `syn` and `quote` to provide the same functionalities.
In order to help review, I tried not to change any operation or code logic in the process, and limit the changes to the upgrade.

Notes:
- `syntex` dependency is completely removed, as well as requirements for `build.rs` and compiler plugins
- As a consequence, this makes compilation faster :)
- Add a custom derive `#[derive|(Packet)]`, and for backwards compatibility also a custom struct attribute `#[packet]`
- for `pnet_packet` calling crates, this is completely transparent, no code has to change
- the `pnet_macros` test suite passes, I also added more tests for `construct_with`, `payload` and `length_fn`
- the patch ends up being quite big. This is mostly due to moving all `<file>.rs.in` to `<file>.rs` in `pnet_packet`. If you really want to avoid that, 89cf5f27b7faac39f81cf355a8ed11176900009b can be dropped

Other points of attention :
- in a proc_macro, env vars from cargo are not available, so I had to replace the uses of `CARGO_CFG_TARGET_ENDIAN`. I used `cfg!(target_endian = "little")`, but I'm not entirely sure this is correct
- the CI is failiing (see https://travis-ci.org/github/chifflier/libpnet) in `compiletest_rs`: `Problem with env var 'DYLD_LIBRARY_PATH': NotPresent'`. This is https://github.com/Manishearth/compiletest-rs/issues/179

Changes since v0.1 (discussed in #355):
- Split huge commit for `pnet_packet` include files in two, first removing old files, and then renaming using git
- Minor fixes/types
- Update documentation (https://github.com/chifflier/libpnet/blob/5a96e6fd830a290875f7ae50161a58a0bfe60d31/docs/using_packet.md) for `Packet` use, and add a section for upgrade instructions
- I'm not sure if directly using `#[derive(Packet)]` (and removing `#[packet]`) is a good thing: there is a trait with with same name (`pnet_packet::Packet`), this could cause naming problems when importing (`use pnet_macros::Packet` vs `use pnet_packet::Packet`).

### CODE REVIEW

**Comment by chifflier** [comment]
Hm, it seems one file changed in the meantime (probably caused by 99502b79713ed742159b93bc95aaad7564b6b070)
Do you want me to rebase PR and force-push ? (or re-submit another PR?)

**Comment by mrmonday** [comment]
Rebasing is fine :)

**Comment by chifflier** [comment]
Hi,
Just a friendly reminder of the PR. Did you have some time to review the code ?

**Comment by dvc94ch** [comment]
neat! hopefully it will get merged soon.

**Review by dvc94ch — COMMENTED** [review]
Maybe merge`libpnet_macro_support` into `libpnet_base`?

**Comment by mrmonday** [comment]
Sorry this has taken forever for me to get around to.

This looks great, thank you for your work - this is long overdue!

**Pull request merged**
