### PR TITLE
transport: Add option to set ECN on the TransportSender socket.

### PR DESCRIPTION
**Pull request by hawkinsw**
Add support for setting the ECN bits on a TransportSender socket for IPv4 and IPv6.

### CODE REVIEW

**Comment by hawkinsw** [comment]
> And, yes, I will fix the CI/CD. Sorry!
> 
> Thank you again!

I think I fixed as much of the CI/CD as I can without venturing too far afield of what this PR does. Let me know what else I can do! 

Thank you!
Will

**Comment by Paul-weqe** [comment]
I like this!!! Congestion Notification. is very important Testing this locally right now. 

Most of the fail checks I had before were due to spelling errors, which are still waiting for this to be merged: https://github.com/libpnet/libpnet/pull/676.

**Comment by hawkinsw** [comment]
> I like this!!! Congestion Notification. is very important Testing this locally right now.
> 

I sincerely, *sincerely* appreciate your enthusiasm. As I said, this crate is amazing. If there is anything else I can do to help, please just let me know!
Will

> Most of the fail checks I had before were due to spelling errors and such so shouldn't worry you too much. If this is merged all should be good #676. Testing locally to see if there is anything else that might be amiss.

**Comment by hawkinsw** [comment]
Just dropping in to add a little feature that I found that I needed -- implementing the `From` trait for `Ecn` `struct`. Please let me know if there is anything I can do to get this PR into shape. I really appreciate the library and hope that this is at least slightly helpful!

**Comment by mrmonday** [comment]
I'd have liked some documentation to go with this, but I'll not hold up merging it since you've been waiting long enough :)

Thank you for your contribution.

**Pull request merged**
