### PR TITLE
Fix merge fallout from pull #147.

### PR DESCRIPTION
**Pull request by mrmonday**
Accidentally lost these changes during rebasing/merging.

### CODE REVIEW

**Comment by mrmonday** [comment]
@alexsult Does this look right? Have I missed anything?

**Comment by alexsult** [comment]
Still the same, "mod Ipv4OptionNumbers" is missing, ipv4_options_length returns the length in words ...
If you want I can modify this file.

**Comment by mrmonday** [comment]
This pull request should add those back in, no?

**Comment by alexsult** [comment]
Sorry I was still asleep. It's OK, the pull requests adds what was missing.

**Comment by mrmonday** [comment]
Haha, that's OK, I only just woke up myself!

@homu r+

**Pull request merged**
