### PR TITLE
Added Ethertypes

### PR DESCRIPTION
**Pull request by itwasscience**
Added a few Ethertypes useful for ISPs.

### CODE REVIEW

**Comment by mrmonday** [comment]
I'm going to trust that all these constants are correct :)

Thank you for your time and effort!

@homu r+

**Comment by itwasscience** [comment]
I checked them twice ! Good luck on this project.

**Comment by mrmonday** [comment]
Did you mean to close this?

Do you still want this to be merged?

**Comment by itwasscience** [comment]
Oh, this was an accident! I'm a bit of a noob at the Github thing.

**Comment by mrmonday** [comment]
Not to worry - I'll reopen it and make sure it gets merged this time :)

@homu r+

**Comment by itwasscience** [comment]
Thank you!

**Comment by mrmonday** [comment]
Looks like homu/travis are having some issues, will merge manually.

Thank you again for your work :)

**Pull request merged**
