### PR TITLE
Edited windows requirements

### PR DESCRIPTION
**Pull request by abusalaa7**
Use winapi in cargo file to fix the issue in #481

### CODE REVIEW

**Comment by mrmonday** [comment]
Why is this necessary?

It should be picked up transitively through libpnet's dependencies, no?

**Comment by stappersg** [comment]
> It should be picked up transitively through libpnet's dependencies, no?

In #481 were two complians of brokeness on MS Windows. A third person offered a solution.

That solution resulted in this merge request.


I think the question _"Why is this necessary?"_ should be left unanswered.

What I further think:
* The patch should be against `Cargo.toml`
* The patch should be accepted
* The question should be _"Whom is harm by this proposed change?"_

**Comment by mrmonday** [comment]
Ah, found it:

https://github.com/libpnet/libpnet/issues/481#issuecomment-834821390

I think the real fix for this would be to change the `winapi` dependency in libpnet to include that feature - that should cause it to "just work" without any manual intervention from users.

I won't have a Windows machine to test this on.

**Comment by abusalaa7** [comment]
I have a windows machine, I will test it.

**Comment by abusalaa7** [comment]
@mrmonday @stappersg - noticed something weird. Building from source on windows, without any changes to `cargo.toml` file doesn't cause the same issue. I can still replicate the issue when using the crate but if I build the source on windows and reference its location on disk, it works fine. I can't confirm if adding `winapi` dependency to cargo file will fix it. Any suggestions?

**Comment by mrmonday** [comment]
Closing due to inactivity.

**Pull request closed without merging**
