### PR TITLE
Fix issue 399 by using u16::from_be_bytes so we aren't using any raw …

### PR DESCRIPTION
**Pull request by hughesac**
This fixes the panic (#399) that was happening when the memory used in checksum calculations was not 16-bit aligned.  The code no longer uses raw pointers so we don't need any checks for alignment.  I ran the pnet_packet unit tests.

### CODE REVIEW

**Comment by JuxhinDB** [comment]
@mrmonday I would really love your thoughts on this one (or @imsnif should you want to pitch in as it affects you).

**Comment by mrmonday** [comment]
I'm in favour of anything that gets rid of unsafe code.

Would be good to get a new unit test for the failing case so we don't regress.

IIRC, the checksum code has been redone a bunch of times to make it faster and fix bugs - so bear that in mind.

**Comment by JuxhinDB** [comment]
Thanks for the input @mrmonday!

@hughesac thanks for the PR (apologies for not mentioning this earlier). Following up on @mrmonday comment, would we be able to include some [regression] tests to sustain the PR?

**Comment by hughesac** [comment]
Yes I should be able to add some tests within the next couple days.

**Comment by JuxhinDB** [comment]
Looking forward. Will keep an eye out for changes.

**Comment by hughesac** [comment]
I've finished adding tests.  Let me know if there are others you would like to see.

**Comment by JuxhinDB** [comment]
Went through the changes and tests added. Apologies for taking a while to follow-up on this. Thanks @hughesac, merging!

**Comment by hughesac** [comment]
@JuxhinDB  Can you make a new release that includes these commits so that dependent projects can get them?

**Comment by JuxhinDB** [comment]
Hey @hughesac -- I set a reminder to do so. But realistically we're looking at mid next week, apologies

**Pull request merged**
